### ISSUE TITLE
Sending mail to encrypted SMTP seems to be broken

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-server#109]
see:
 - https://forum.image.sc/t/password-reset-email-config/35701/6
 - https://forum.image.sc/t/how-to-debug-the-omero-mail-system/42731/3
 - https://docs.openmicroscopy.org/omero/5.6/sysadmins/config.html#mail
 - https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html

Investigations into the above forum threads seems to point to some combination of current Java version, mail providers (minimally gmail), and the current server version (5.6.1) not being able to send mail over SSL/TCP. (Examples in Dundee work when sending to unencrypted servers)

**Comment by joshmoore** [comment]
Configuration used for testing:

```
grep -A30 omeroserver: docker-compose.yml
  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_mail_bean: "localMailSender"
      CONFIG_omero_mail_auth: "true"
      CONFIG_omero_mail_config: "true"
      CONFIG_omero_mail_from: "${EMAIL}"
      CONFIG_omero_mail_host: smtp.gmail.com
      CONFIG_omero_mail_port: 465
      CONFIG_omero_mail_username: "${EMAIL}"
      CONFIG_omero_mail_password: "${PASSWORD}"
      CONFIG_omero_mail_smtp_debug: "true"
      CONFIG_omero_mail_smtp_starttls_enable: "true"
      CONFIG_omero_mail_transport_protocol: "smtps"
      CONFIG_omero_mail_smtp_socketFactory_class: javax.net.ssl.SSLSocketFactory
      CONFIG_omero_mail_smtp_socketFactory.port: 465
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
      - "./files/ome:/opt/omero/server/OMERO.server/etc/ome"
```

```
$ cat files/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

<!--
  Mail resources
  =======================================================================
-->

  <bean id="localMailSender" class="org.springframework.aop.framework.ProxyFactoryBean">
      <description>
          Default mail sender uses a swappable target source so that for
          testing we can replace it with a no-op version.
      </description>
      <property name="targetSource" ref="local-mailSenderTargetSource"/>
  </bean>

  <bean id="local-mailSenderTargetSource"
      class="org.springframework.aop.target.HotSwappableTargetSource">
      <constructor-arg ref="local-javaMailSenderImpl"/>
  </bean>

  <!-- configure the MailSender with the authenticated session -->
  <bean id="local-javaMailSenderImpl"
      class="org.springframework.mail.javamail.JavaMailSenderImpl">
      <property name="host" value="${omero.mail.host}" />
      <property name="port" value="${omero.mail.port}" />
      <property name="protocol" value="${omero.mail.transport.protocol}" />
      <property name="session" ref="local-mailSession" />
      <property name="javaMailProperties">
          <props>
              <prop key="mail.smtp.sendpartial">true</prop>
          </props>
      </property>
  </bean>

  <!-- setup an authenticated session -->
  <bean id="local-mailSession" class="javax.mail.Session" factory-method="getInstance">
      <constructor-arg>
          <props>
              <prop key="mail.smtp.ssl">true</prop>
              <prop key="mail.smtp.ssl.enable">true</prop>
              <prop key="mail.smtp.ssl.trust">true</prop>
              <!-- existing -->
              <prop key="mail.smtps.auth">${omero.mail.smtp.auth}</prop>
              <prop key="mail.smtps.debug">${omero.mail.smtp.debug}</prop>
              <prop key="mail.smtps.connectiontimeout">${omero.mail.smtp.connectiontimeout}</prop>
              <prop key="mail.smtps.sendpartial">true</prop>
              <prop key="mail.smtps.starttls.enable">${omero.mail.smtp.starttls.enable}</prop>
              <prop key="mail.smtps.socketFactory.port">${omero.mail.smtp.socketFactory.port}</prop>
              <prop key="mail.smtps.socketFactory.class">${omero.mail.smtp.socketFactory.class}</prop>
              <prop key="mail.smtps.socketFactory.fallback">${omero.mail.smtp.socketFactory.fallback}</prop>
              <prop key="mail.smtps.timeout">${omero.mail.smtp.timeout}</prop>
          </props>
      </constructor-arg>
      <constructor-arg ref="local-smtpAuthenticator" />
  </bean>

  <!-- Authenticator implementation -->
  <bean id="local-smtpAuthenticator" class="ome.security.SmtpAuthenticator">
      <constructor-arg value="${omero.mail.username}" />
      <constructor-arg value="${omero.mail.password}" />
  </bean>

</beans>
```
