### ISSUE TITLE
Failing CI builds due to Ubuntu 24.04 being the latest

### ISSUE THREAD

**Issue by sbesson** [ome/omero-server#186]
Noticed while working on #185 and receiving build errors in the GitHub workflow on my fork

The latest scheduled runs of GitHub actions have been consistently failing for the `ubuntu-latest` job with

```
/opt/ice-3.6.5/bin/slice2java: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

Looking at the history, the timing of these failures matches with the switch of `ubuntu-latest` from Ubuntu 22.04 to Ubuntu 24.04 a few weeks ago - https://github.com/actions/runner-images?tab=readme-ov-file#available-images

At the moment, the current logic makes is the following
- the GitHub workflow inherits a shared workflow https://github.com/ome/omero-server/blob/5b5a78233c34e2ad99316686ad4272f520d7bb1c/.github/workflows/gradle.yml#L12
- this parent workflow specifies `ubuntu-latest` in the build matrix and uses `ome/action-ice@v2.1` for installing the Ice prerequisites - https://github.com/ome/action-workflows/blob/c3b85d025fa51089e9eb4414b37121ca271dab8b/.github/workflows/gradle_build.yml#L26-L33
- `ome/action-ice` downloads the pre-built Ubuntu 22.04 Ice binary and installs it https://github.com/ome/action-ice/blob/c3f8f22816daaa80a0f32e0d175e97446736c867/action.yml#L25

Without reworking this logic entirely, a few options I can think of:
- update https://github.com/ome/action-workflows to pin it to `ubuntu-2204`
- update https://github.com/ome/action-ice to download https://github.com/glencoesoftware/zeroc-ice-ubuntu2404-x86_64/releases/tag/20240619, release a new version of the action for Ubuntu 24.04 and consume it in https://github.com/ome/action-workflows 
- remove the `ome.action-ice` logic from https://github.com/ome/action-workflows and move it to the GitHub workflow within this repository

**Comment by jburel** [comment]
While looking at, I encounter a problem with Python action. The same happened on Ubuntu 22.04
This might have been a blip

**Comment by jburel** [comment]
I am getting this error now
```
Run actions/setup-python@v5
  with:
    python-version: 10
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    ICE_HOME: /opt/ice-3.6.5
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.26-4/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.26-4/x64
```
leads to 
```
Version 10 was not found in the local cache
  Error: The version '10' with architecture 'x64' was not found for Ubuntu 22.04.
```
